### ISSUE TITLE
Serial Exception: device reports readiness to read but returned no data

### ISSUE THREAD

**Issue by jericholab** [jericholab/rdl#21]
The pilot user reported several failures of the RDL-syncing script. The error happens both with the service and the manual execution in the terminal.  The exact error is:
Traceback (most recent call last):
  File "/home/orangepi/SHELF3/WIRED-logging-RDL-USB0.py", line 87, in <module>
    data = ser.readline().decode('ascii')
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 595, in read
    raise SerialException(
serial.serialutil.SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)

The error happens about once a day. 

![20240328_164951](https://github.com/jericholab/rdl/assets/99691909/3b9b4ccb-4759-47a4-9dba-35faa61485ba)

**Comment by jericholab** [comment]
It would be useful to be able to reproduce the error on the Montreal unit. I also wonder if the quantity of active sensors play a role. They are currently ALL active on Greenhouse. It would be possible active ALL on Montreal or  deactivate some on Greenhouse.
